export default {
    SIGNIN: "Sign In",
    SIGNUP: "Sign Up",
    HOME:"home",
    REQUIRED: "This field is required.",
    INVALID_EMAIL: "Email is invalid.",
    NO_SPACES_ALLOWED:"No spaces allowed",
    NAME:"Name",
    EMAIL_ADDRESS: "Email Address",
    PASSWORD: "Password",
    BACK_TO_SIGNUP:"Don't have an account?",
    PASSWORD_MIN_LENGTH: "Password must be at least 8 characters long",
    PASSWORD_MUST_CONTAIN_LETTER: "Password must contain at least one letter",
    PASSWORD_MUST_CONTAIN_NUMBER: "Password must contain at least one number",
    PASSWORD_MUST_CONTAIN_SPECIAL_CHAR: "Password must contain at least one special character",
    SUCCESSFULLY_SIGNUP_MESSAGE: "You have sign up successfully",
    SUCCESSFULLY_SIGIN_MESSAGE: "You have sign in successfully",
    WELCOME_MSG:"Welcome to the application !",
    SIGNOUT: "Sign Out",
}